language: go
go:
- 1.x
go_import_path: github.com/Wraparound/wrap
env:
  matrix:
  - GO111MODULE=on
before_install:
- go get -v github.com/josephspurrier/goversioninfo/cmd/goversioninfo
script:
- make test
- make nightlies
dist: xenial
addons:
  apt:
    packages:
    - nsis
before_deploy:
- export TRAVIS_TAG=$(git tag | tail -n 1)
deploy:
  provider: releases
  api_key:
    secure: WzBYsJGhELhVWVypUZCi4rT8c9iYiRVw40pRuFHIEVX3UsVdAbLclki0uHhodykB9f97BEi2HMoFEXNI6aRTc/tMVhp7ci5lNYT+3Hk78lGyV7Jsnt3j7wC7AUgawwUFxfkX1B8IdxHkyLbICx4nc+hGJKaEAC2X3u5fAFf+Rohap22oycON9pJKb1Tx3jjKJyAYk6Qug7W7VQ1Txi+dvwPkyrCUUwL+wcUVsji1QTnEWvWtrSh5uWzSIvDy/U4w1lm6imJwhpBr9qXsj2u4lo699H6hFrCnyH8xHXLQpTBWg3vjYKzXbmiQECnRb1RA/EtjmaaLBHCY1QxiB1rNfNxoP+fS/wo4NC4jn8Ygm11/IwTlxcOJnR56koaELopFYme9mJDydj0nXJ10kmqsEl/0LlUJJI6InqbCwxWc5ioWSIRfZZhMjXbAJI43WJR7pVXbcSj5SHLfGB50AI8lwkvjD6LCMB7OkVMowJfksaIdMb4t2wIqHd1imEKqvnU33DAwKLHR7ScVjdZQ3leQ34ockmsh+UC8iQCJhUo9t/SPE7L1eV6N/hLPLWICn3/RiwnLfjzJQxZWvsJ/Pb/JHfk2oQyDPuuahmgjJFB3TJZZbfjfPhhSf4ClIePhaUAVU/8uMU8qnBB/BqHMYju2S5c2AQ5UmLMFWRls40xRHNk=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  overwrite: true
  on:
    repo: Wraparound/wrap
    branch: master
