language: go

go:
  - 1.x

go_import_path: github.com/Wraparound/wrap

env:
  - GO111MODULE=on

before_install:
  - go get -v github.com/josephspurrier/goversioninfo/cmd/goversioninfo

script:
  - make test
  - make nightlies

dist: xenial

addons:
  apt:
    packages:
      - nsis

before_deploy:
  - TRAVIS_TAG=$(git tag | tail -n 1)

deploy:
  provider: releases
  file_glob: true
  file: dist/*
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
