language: go
go:
- 1.x
go_import_path: github.com/Wraparound/wrap
env:
  matrix:
  - GO111MODULE=on
before_install:
- go get -v github.com/josephspurrier/goversioninfo/cmd/goversioninfo
script:
- make test
- make nightlies
dist: xenial
# addons:
#   apt:
#     packages:
#     - nsis
# before_deploy:
# - export TRAVIS_TAG=$(git tag | tail -n 1)
# deploy:
#   provider: releases
#   api_key:
#     secure: bJvXdF+9APiK2CEUEXir+m9AcpbcYHV5gySWRRbcvfGOgxomHAjPP1h2X0IxAc6HcNlJgwcnkz+6BCZRkWzvLD6HJ/3e2voKFWdUCP7ZfRRlojUfGx6/FWVc7asfMGyVI6SrrfIzkJy/Ajq1kJcO6gvqyUaHwtSneW8nt0gVQQQljpEnvB69HkfI2Oe1p6jJsTMQJR1U9Wk+Q8LYd6BJ6ij0MiuD+Nus+cGee33DQaMIUsRSCE+ZGdwRPrPcXsRpThAUwhAUWJiiHplgyicfwnviV61j5WZE9ZLE9xSty8awyyFW/f9oa3I1U4dzGhmYTAGqnnHIRG2iPSrdunU3FNFJW+96NbccxTJAy8HwQHnSgmnyg5mDkaK5nKg15xtdCa+Z8zpAozWYMCWfBQdP2sBnx2jSBTHz5vrjI6cckRiS6NpTjIVlHJbwYb4Ni0g9ek3o0HfZjHkMrXLqyiqRzLK1WUuRFZ48voOV9NLwvhXC96GCuPXclxb5GCG6X7G8zeBjFC7qStxlOHlo2yxtjJaZKpwKd/jZ7skbHAPMh/OfV3I+mk+kKoYzScV7mRepzvNDJWElWzTWHDsZIwe71kWNA9RfkdNhEPH1Dd8PtBzSPQicXqzjk1LIDtnxVToe9J+i9Ib6JM2x752PNdj14K6yNljeiM2nUWY48GnS8as=
#   file_glob: true
#   file: dist/*
#   skip_cleanup: true
#   overwrite: true
#   on:
#     repo: Wraparound/wrap
#     branch: master
