# name: feltix
version: "0.0.1"
summary: A Fountain export tool with some extra's...
description: Feltix is a parser/exporter for the Founatin format which also adds some extensions to said format.
grade: devel
confinement: strict

apps:
  feltix:
    command: feltix

parts:
  gnu-hello:
    plugin: go
    go-packages: [github.com/Feltix/feltix]
