name: feltix
version: "v0.1.3"
summary: A Fountain export tool with some extra's...
description: Feltix is a parser/exporter for the Fountain format which also adds some extensions to said format.
grade: stable
confinement: strict

apps:
  feltix:
    command: feltix
    completer: complete.sh
    plugs:
      - home
      - desktop
      - removable-media

parts:
  feltix-cli:
    plugin: go
    go-packages: [github.com/Feltix/feltix]
