name: wrap
version: "v0.3.3"
summary: A Fountain export tool with some extra's...
description: Wrap is a parser/exporter for the Fountain format which also adds some extensions to said format.
base: core18
grade: stable
confinement: strict

parts:
  wrap-cli:
    plugin: go
    go-importpath: github.com/eprovst/wrap
    go-packages: [github.com/eprovst/wrap/cmd/wrap]
    go-buildtags: [ldflags '-s -w']

apps:
  wrap:
    command: wrap
    completer: bash-complete.sh
    plugs:
      - home
      - desktop
      - removable-media
