name: wrap
version: "v0.1.5"
summary: A Fountain export tool with some extra's...
description: Wrap is a parser/exporter for the Fountain format which also adds some extensions to said format.
grade: stable
confinement: strict

apps:
  wrap:
    command: wrap
    completer: complete.sh
    plugs:
      - home
      - desktop
      - removable-media

parts:
  wrap-cli:
    plugin: go
    go-importpath: github.com/Wraparound/wrap
    go-packages: [github.com/Wraparound/wrap]
    go-buildtags: [ldflags '-s -w']